### ISSUE TITLE
Regression: SC 1.4.4 and SCUI break TextField in latest firefox

### ISSUE THREAD

**Issue by rvalle** [etgryphon/sproutcore-ui#3]
Hi there!!

When updating to the latest SC 1.4.4 the text fields controls stopped rendering correctly in latest firefox for OSX. 

I have been investigating and I came to the conclusion that this rendering issue happens only in presence of SCUI framework. I can reproduce it using the sample_controls application part of the sproutcore_samples. Just adding the SCUI framework will make it happen.

**Comment by rvalle** [comment]
It is actually to do with calendar.css, I noticed that some styles from this file are been applied to the TextField. Removing calendar.css workarounded the issue.

**Comment by etgryphon** [comment]
i have to rework all the css to fix the theming
